export const generalQuestions = [
      {
        type: "multiple",
        difficulty: "medium",
        category: "General Knowledge",
        question: "What is the unit of currency in Laos?",
        correct_answer: "Kip",
        incorrect_answers: ["Ruble", "Konra", "Dollar"],
      },
      {
        type: "boolean",
        difficulty: "easy",
        category: "General Knowledge",
        question:
          "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.",
        correct_answer: "False",
        incorrect_answers: ["True"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question: "Red Vines is a brand of what type of candy?",
        correct_answer: "Licorice",
        incorrect_answers: ["Lollipop", "Chocolate", "Bubblegum"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question: "When was the Playstation 3 released?",
        correct_answer: "November 11, 2006",
        incorrect_answers: [
          "January 8, 2007",
          "December 25, 2007",
          "July 16, 2006",
        ],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question:
          "Which country, not including Japan, has the most people of Japanese descent?",
        correct_answer: "Brazil",
        incorrect_answers: ["China", "South Korea", "United States of America"],
      },
      {
        type: "boolean",
        difficulty: "easy",
        category: "General Knowledge",
        question: "French is an official language in Canada.",
        correct_answer: "True",
        incorrect_answers: ["False"],
      },
      {
        type: "multiple",
        difficulty: "hard",
        category: "General Knowledge",
        question:
          "In flight systems, what does the initialism &quot;TCAS&quot; stand for?",
        correct_answer: "Traffic Collision Avoidance System",
        incorrect_answers: [
          "Traffic Communication Alert System",
          "Traffic Configuration Alignment System",
          "Traffic Call-sign Abbreviation System",
        ],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "General Knowledge",
        question: "What is the full title of the Prime Minister of the UK?",
        correct_answer: "First Lord of the Treasury",
        incorrect_answers: [
          "Duke of Cambridge",
          "Her Majesty&#039;s Loyal Opposition",
          "Manager of the Crown Estate",
        ],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question: "How many colors are there in a rainbow?",
        correct_answer: "7",
        incorrect_answers: ["8", "9", "10"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "General Knowledge",
        question: "Whose greyscale face is on the kappa emoticon on Twitch?",
        correct_answer: "Josh DeSeno",
        incorrect_answers: ["Justin DeSeno", "John DeSeno", "Jimmy DeSeno"],
      },
      {
        type: "boolean",
        difficulty: "medium",
        category: "General Knowledge",
        question:
          "A pencil&#039;s lead is typically made from graphite, not lead",
        correct_answer: "True",
        incorrect_answers: ["False"],
      },
      {
        type: "boolean",
        difficulty: "medium",
        category: "General Knowledge",
        question:
          "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.",
        correct_answer: "True",
        incorrect_answers: ["False"],
      },
      {
        type: "boolean",
        difficulty: "easy",
        category: "General Knowledge",
        question:
          "Vietnam&#039;s national flag is a red star in front of a yellow background.",
        correct_answer: "False",
        incorrect_answers: ["True"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "General Knowledge",
        question: "What is the Portuguese word for &quot;Brazil&quot;?",
        correct_answer: "Brasil",
        incorrect_answers: ["Brazil", "Brasilia", "Bras&iacute;l"],
      },
      {
        type: "multiple",
        difficulty: "hard",
        category: "General Knowledge",
        question:
          "Which product did Nokia, the telecommunications company, originally sell?",
        correct_answer: "Paper",
        incorrect_answers: ["Phones", "Computers", "Processors"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question:
          "Which one of the following rhythm games was made by Harmonix?",
        correct_answer: "Rock Band",
        incorrect_answers: [
          "Meat Beat Mania",
          "Guitar Hero Live",
          "Dance Dance Revolution",
        ],
      },
      {
        type: "multiple",
        difficulty: "hard",
        category: "General Knowledge",
        question:
          "Disney&#039;s Haunted Mansion is home to a trio of Hitchhiking Ghosts. Which of these is NOT one of them?",
        correct_answer: "Harry",
        incorrect_answers: ["Gus", "Phineas", "Ezra"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question: "What is &quot;dabbing&quot;?",
        correct_answer: "A dance",
        incorrect_answers: ["A medical procedure", "A sport", "A language"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "General Knowledge",
        question: "Who is the founder of &quot;The Lego Group&quot;?",
        correct_answer: "Ole Kirk Christiansen",
        incorrect_answers: [
          " Jens Niels Christiansen",
          "Kirstine Christiansen",
          " Gerhardt Kirk Christiansen",
        ],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "General Knowledge",
        question:
          "Where does water from Poland Spring water bottles come from?",
        correct_answer: "Maine, United States",
        incorrect_answers: [
          "Hesse, Germany",
          "Masovia, Poland",
          "Bavaria, Poland",
        ],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question: "What is the largest organ of the human body?",
        correct_answer: "Skin",
        incorrect_answers: ["Heart", "large Intestine", "Liver"],
      },
      {
        type: "multiple",
        difficulty: "hard",
        category: "General Knowledge",
        question:
          "In the MMO RPG &quot;Realm of the Mad God&quot;, what dungeon is widely considered to be the most difficult?",
        correct_answer: "The Shatter&#039;s",
        incorrect_answers: [
          "Snake Pit",
          "The Tomb of the Acient&#039;s",
          "The Puppet Master&#039;s Theater",
        ],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question:
          "The buried remains of which English explorer of Australia were found in London  in January 2019? ",
        correct_answer: "Matthew Flinders",
        incorrect_answers: ["William Bourke", "Abel Tasman", "Dirk Hartog"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "General Knowledge",
        question:
          "What was the name given to Japanese military dictators who ruled the country through the 12th and 19th Century?",
        correct_answer: "Shogun",
        incorrect_answers: ["Ninja", "Samurai", "Shinobi"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question: "Who is the author of Jurassic Park?",
        correct_answer: "Michael Crichton",
        incorrect_answers: [
          "Peter Benchley",
          "Chuck Paluhniuk",
          "Irvine Welsh",
        ],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "General Knowledge",
        question: "Where did the pineapple plant originate?",
        correct_answer: "South America",
        incorrect_answers: ["Hawaii", "Europe", "Asia"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question: "When was the website reddit founded ?",
        correct_answer: "2005",
        incorrect_answers: ["2008", "2004", "2006"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question: "Who is the youngest person to receive a Nobel Prize?",
        correct_answer: "Malala Yousafzai",
        incorrect_answers: [
          "Lawrence Bragg",
          "Werner Heisenberg",
          "Yasser Arafat",
        ],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question: "What is the first book of the Old Testament?",
        correct_answer: "Genesis",
        incorrect_answers: ["Exodus", "Leviticus", "Numbers"],
      },
      {
        type: "boolean",
        difficulty: "easy",
        category: "General Knowledge",
        question: "The National Animal of Scotland is the Unicorn.",
        correct_answer: "True",
        incorrect_answers: ["False"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "General Knowledge",
        question: "Which of the following is NOT one of Aesop&#039;s fables?",
        correct_answer: "The Fox and the Hound",
        incorrect_answers: [
          "The Fox and the Grapes",
          "The Tortoise and the Hare",
          "The Frog and the Ox",
        ],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "General Knowledge",
        question:
          "In a standard set of playing cards, which is the only king without a moustache?",
        correct_answer: "Hearts",
        incorrect_answers: ["Spades", "Diamonds", "Clubs"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question:
          "In &quot;Katamari Damacy&quot;, you control a character known as:",
        correct_answer: "The Prince",
        incorrect_answers: ["Fujio", "Ichigo ", "Foomin"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question: "What organ of the body produces bile?",
        correct_answer: "Liver",
        incorrect_answers: ["Gallbladder", "Pancreas", "Stomach"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question:
          "Which canal connects the Mediterranean Sea with the Red Sea?",
        correct_answer: "Suez Canal",
        incorrect_answers: ["Panama Canal", "Sinai Canal", "Qaraqum Canal"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question: "Which one of these is not a typical European sword design?",
        correct_answer: "Scimitar",
        incorrect_answers: ["Falchion", "Ulfberht", "Flamberge"],
      },
      {
        type: "boolean",
        difficulty: "medium",
        category: "General Knowledge",
        question: "Pure water effectively conducts electricity ",
        correct_answer: "False",
        incorrect_answers: ["True"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question:
          "Which company did Valve cooperate with in the creation of the Vive?",
        correct_answer: "HTC",
        incorrect_answers: ["Oculus", "Google", "Razer"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "General Knowledge",
        question: "What is the world&#039;s most expensive spice by weight?",
        correct_answer: "Saffron",
        incorrect_answers: ["Cinnamon", "Cardamom", "Vanilla"],
      },
      {
        type: "multiple",
        difficulty: "hard",
        category: "General Knowledge",
        question: "What is the romanized Korean word for &quot;heart&quot;?",
        correct_answer: "Simjang",
        incorrect_answers: ["Aejeong", "Jeongsin", "Segseu"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question: "What is Cynophobia the fear of?",
        correct_answer: "Dogs",
        incorrect_answers: ["Birds", "Flying", "Germs"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "General Knowledge",
        question:
          "Which of these is the name of a Japanese system of alternative medicine, literally meaning &quot;finger pressure&quot;?",
        correct_answer: "Shiatsu",
        incorrect_answers: ["Ukiyo", "Majime", "Ikigai"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question: "The Canadian $1 coin is colloquially known as a what?",
        correct_answer: "Loonie",
        incorrect_answers: ["Boolie", "Foolie", "Moodie"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "General Knowledge",
        question:
          "Which slogan did the fast food company, McDonald&#039;s, use before their &quot;I&#039;m Lovin&#039; It&quot; slogan?",
        correct_answer: "We Love to See You Smile",
        incorrect_answers: [
          "Why Pay More!?",
          "Have It Your Way",
          "Making People Happy Through Food",
        ],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question: "What does the F stand for in the FBI?",
        correct_answer: "Federal",
        incorrect_answers: ["Foreign", "Formal", "First"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "General Knowledge",
        question:
          "The architect known as Le Corbusier was an important figure in what style of architecture?",
        correct_answer: "Modernism",
        incorrect_answers: ["Neoclassical", "Baroque", "Gothic Revival"],
      },
      {
        type: "boolean",
        difficulty: "medium",
        category: "General Knowledge",
        question:
          "The bikini is named after the &quot;Bikini Atoll&quot;, an island where the United States conducted tests on atomic bombs.",
        correct_answer: "True",
        incorrect_answers: ["False"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question: "What is the Spanish word for &quot;donkey&quot;?",
        correct_answer: "Burro",
        incorrect_answers: ["Caballo", "Toro", "Perro"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "General Knowledge",
        question:
          "According to the nursery rhyme, what fruit did Little Jack Horner pull out of his Christmas pie?",
        correct_answer: "Plum",
        incorrect_answers: ["Apple", "Peach", "Pear"],
      },
    ]