export const sportQuestions = [
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question: "Who won the &quot;Champions League&quot; in 1999?",
    correct_answer: "Manchester United",
    incorrect_answers: ["Barcelona", "Bayern Munich", "Liverpool"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question: "How many French Open&#039;s did Bj&ouml;rn Borg win?",
    correct_answer: "6",
    incorrect_answers: ["4", "9", "2"],
  },
  {
    type: "boolean",
    difficulty: "medium",
    category: "Sports",
    question: "Tennis was once known as Racquetball.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Sports",
    question:
      "Which male player won the gold medal of table tennis singles in 2016 Olympics Games?",
    correct_answer: "Ma Long (China)",
    incorrect_answers: [
      "Zhang Jike (China)",
      "Jun Mizutani (Japan)",
      "Vladimir Samsonov (Belarus)",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Sports",
    question:
      "In Baseball, how many times does the ball have to be pitched outside of the strike zone before the batter is walked?",
    correct_answer: "4",
    incorrect_answers: ["1", "2", "3"],
  },
  {
    type: "boolean",
    difficulty: "medium",
    category: "Sports",
    question:
      "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    type: "boolean",
    difficulty: "medium",
    category: "Sports",
    question:
      "Skateboarding was included in the 2020 Summer Olympics in Tokyo.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question:
      "What city did the Lakers represent before relocating to Los Angeles?",
    correct_answer: "Minneapolis",
    incorrect_answers: ["Philadelphia", "Chicago", "San Francisco"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Sports",
    question:
      "Which of these European cities was the first to host the modern Summer Olympic Games three times?",
    correct_answer: "London",
    incorrect_answers: ["Paris", "Athens", "Rome"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Sports",
    question:
      "Who won the premier league title in the 2015-2016 season following a fairy tale run?",
    correct_answer: "Leicester City",
    incorrect_answers: ["Tottenham Hotspur", "Watford", "Stoke City"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Sports",
    question:
      "How many players are there in an association football/soccer team?",
    correct_answer: "11",
    incorrect_answers: ["10", "9", "8"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Sports",
    question: "How many points did LeBron James score in his first NBA game?",
    correct_answer: "25",
    incorrect_answers: ["19", "69", "41"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question: "Hockey player Wayne Gretzky was born in what Canadian province?",
    correct_answer: "Ontario",
    incorrect_answers: ["British Columbia", "Quebec", "Alberta"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Sports",
    question: "Which country hosted the 2020 Summer Olympics?",
    correct_answer: "Japan",
    incorrect_answers: ["China", "Australia", "Germany"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Sports",
    question:
      "Which year did Jenson Button won his first ever Formula One World Drivers&#039; Championship?",
    correct_answer: "2009",
    incorrect_answers: ["2010", "2007", "2006"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question:
      "Which sport is NOT traditionally played during the Mongolian Naadam festival?",
    correct_answer: "American Football",
    incorrect_answers: ["Wrestling", "Archery", "Horse-Racing"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question:
      "What is the exact length of one non-curved part in Lane 1 of an Olympic Track?",
    correct_answer: "84.39m",
    incorrect_answers: ["100m", "100yd", "109.36yd"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question: "What year was hockey legend Wayne Gretzky born?",
    correct_answer: "1961",
    incorrect_answers: ["1965", "1959", "1963"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Sports",
    question:
      "Which city did the former NHL team &quot;The Nordiques&quot; originiate from?",
    correct_answer: "Quebec City",
    incorrect_answers: ["Houston", "Montreal", "New York"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question: "What is the highest belt you can get in Taekwondo?",
    correct_answer: "Black",
    incorrect_answers: ["White", "Red", "Green"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question: "How many scoring zones are there on a conventional dart board?",
    correct_answer: "82",
    incorrect_answers: ["62", "42", "102"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question: "In a game of snooker, what colour ball is worth 3 points?",
    correct_answer: "Green",
    incorrect_answers: ["Yellow", "Brown", "Blue"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question: "Which soccer team won the Copa Am&eacute;rica Centenario 2016?",
    correct_answer: "Chile",
    incorrect_answers: ["Argentina", "Brazil", "Colombia"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Sports",
    question:
      "Which female player won the gold medal of table tennis singles in 2016 Olympics Games?",
    correct_answer: "DING Ning (China)",
    incorrect_answers: [
      "LI Xiaoxia (China)",
      "Ai FUKUHARA (Japan)",
      "Song KIM (North Korea)",
    ],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Sports",
    question: "Where was the Games of the XXII Olympiad held?",
    correct_answer: "Moscow",
    incorrect_answers: ["Barcelona", "Tokyo", "Los Angeles"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Sports",
    question:
      "In bowling, what is the term used for getting three consecutive strikes?",
    correct_answer: "Turkey",
    incorrect_answers: ["Flamingo", "Birdie", "Eagle"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Sports",
    question: "Which team won the 2015-16 English Premier League?",
    correct_answer: "Leicester City",
    incorrect_answers: ["Liverpool", "Cheslea", "Manchester United"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Sports",
    question: "Who won the 2016 Formula 1 World Driver&#039;s Championship?",
    correct_answer: "Nico Rosberg",
    incorrect_answers: ["Lewis Hamilton", "Max Verstappen", "Kimi Raikkonen"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Sports",
    question: "In Canadian football, scoring a rouge is worth how many points?",
    correct_answer: "1",
    incorrect_answers: ["2", "3", "4"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question: "Who was the top scorer of the 2014 FIFA World Cup?",
    correct_answer: "James Rodr&iacute;guez",
    incorrect_answers: ["Thomas M&uuml;ller", "Lionel Messi", "Neymar"],
  },
  {
    type: "boolean",
    difficulty: "medium",
    category: "Sports",
    question: "The Olympics tennis court is a giant green screen.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    type: "boolean",
    difficulty: "medium",
    category: "Sports",
    question:
      "In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question:
      "Which Formula 1 driver switched teams in the middle of the 2017 season?",
    correct_answer: "Carlos Sainz Jr.",
    incorrect_answers: ["Daniil Kvyat", "Jolyon Palmer", "Rio Haryanto"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Sports",
    question: "Which NFL team plays for New England?",
    correct_answer: "Patriots",
    incorrect_answers: ["Chiefs", "Dolphins", "49ers"],
  },
  {
    type: "boolean",
    difficulty: "easy",
    category: "Sports",
    question: "There are a total of 20 races in Formula One 2016 season.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question:
      "Who won the 2015 College Football Playoff (CFP) National Championship? ",
    correct_answer: "Ohio State Buckeyes",
    incorrect_answers: [
      "Alabama Crimson Tide",
      "Clemson Tigers",
      "Wisconsin Badgers",
    ],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Sports",
    question:
      "Prior to 2018, which car company is the only Japanese company which won the 24 Hours of Le Mans?",
    correct_answer: "Mazda",
    incorrect_answers: ["Toyota", "Subaru", "Nissan"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Sports",
    question: "What team did England beat to win in the 1966 World Cup final?",
    correct_answer: "West Germany",
    incorrect_answers: ["Soviet Union", "Portugal", "Brazil"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Sports",
    question: "Which team has won the most Stanley Cups in the NHL?",
    correct_answer: "Montreal Canadians",
    incorrect_answers: [
      "Chicago Blackhawks",
      "Toronto Maple Leafs",
      "Detroit Red Wings",
    ],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Sports",
    question: "With which doubles partner did John McEnroe have most success?",
    correct_answer: "Peter Fleming",
    incorrect_answers: ["Mark Woodforde", "Michael Stich", "Mary Carillo"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question: "In what sport does Fanny Chmelar compete for Germany?",
    correct_answer: "Skiing",
    incorrect_answers: ["Swimming", "Showjumping", "Gymnastics"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Sports",
    question:
      "What is the full name of the footballer &quot;Cristiano Ronaldo&quot;?",
    correct_answer: "Cristiano Ronaldo dos Santos Aveiro",
    incorrect_answers: [
      "Cristiano Ronaldo los Santos Diego",
      "Cristiano Armando Diego Ronaldo",
      "Cristiano Luis Armando Ronaldo",
    ],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question:
      "Which of the following Grand Slam tennis tournaments occurs LAST?",
    correct_answer: "US Open",
    incorrect_answers: ["French Open", "Wimbledon", "Australian Open"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question:
      "Who was the British professional wrestler Shirley Crabtree better known as?",
    correct_answer: "Big Daddy",
    incorrect_answers: ["Giant Haystacks", "Kendo Nagasaki", "Masambula"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question: "Which country is hosting the 2022 FIFA World Cup?",
    correct_answer: "Qatar",
    incorrect_answers: ["Uganda", "Vietnam", "Bolivia"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Sports",
    question: "The AHL affiliate team of the Boston Bruins is named what?",
    correct_answer: "Providence Bruins",
    incorrect_answers: [
      "New Haven Bruins",
      "Cambridge Bruins",
      "Hartford Bruins",
    ],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question:
      "What was Sir Donald Bradman&#039;s batting average in test matches?",
    correct_answer: "99.94",
    incorrect_answers: ["100", "69.51", "44.78"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Sports",
    question:
      "Which African American is in part responsible for integrating  Major League baseball?",
    correct_answer: "Jackie Robinson",
    incorrect_answers: ["Curt Flood", "Roy Campanella", "Satchell Paige"],
  },
  {
    type: "boolean",
    difficulty: "medium",
    category: "Sports",
    question:
      "The first episode of WWF Monday Night RAW aired on January 11, 1990.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Sports",
    question:
      "Which German sportswear company&#039;s logo is the &#039;Formstripe&#039;?",
    correct_answer: "Puma",
    incorrect_answers: ["Nike", "Adidas", "Reebok"],
  },
];
