export const geographyQuestions = [
      {
        type: "multiple",
        difficulty: "easy",
        category: "Geography",
        question: "Which of the following Japanese islands is the biggest?",
        correct_answer: "Honshu",
        incorrect_answers: ["Hokkaido", "Shikoku", "Kyushu"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question: "What city  has the busiest airport in the world?",
        correct_answer: "Atlanta, Georgia USA",
        incorrect_answers: [
          "London, England",
          "Chicago,Illinois ISA",
          "Tokyo,Japan",
        ],
      },
      {
        type: "multiple",
        difficulty: "hard",
        category: "Geography",
        question: "Which is not a country in Africa?",
        correct_answer: "Guyana",
        incorrect_answers: ["Senegal", "Liberia", "Somalia"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question: "What is the capital of British Columbia, Canada?",
        correct_answer: "Victoria",
        incorrect_answers: ["Vancouver", "Hope", "Kelowna"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question: "Broome is a town in which state of Australia?",
        correct_answer: "Western Australia",
        incorrect_answers: [
          "Northern Territory",
          "South Australia",
          "Tasmania",
        ],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question:
          "Which country claims ownership of the disputed state Kosovo?",
        correct_answer: "Serbia",
        incorrect_answers: ["Croatia", "Albania", "Macedonia"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Geography",
        question: "Which US state is nicknamed &quot;The Golden State&quot;?",
        correct_answer: "California",
        incorrect_answers: ["Florida", "New Mexico", "Alaska"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question:
          "How many sovereign states are members of the United Nations?",
        correct_answer: "195",
        incorrect_answers: ["201", "153", "178"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question:
          "Which of the following countries is within the Eurozone but outside of the Schengen Area?",
        correct_answer: "Cyprus",
        incorrect_answers: ["Malta", "Greece", "Portugal"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question: "Which is the world&#039;s longest river?",
        correct_answer: "Nile",
        incorrect_answers: ["Missouri", "Amazon", "Yangtze"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question: "What is the highest mountain in the world?",
        correct_answer: "Mt. Everest",
        incorrect_answers: [
          "Mount Godwin Austen",
          "Kangchenjunga",
          "Annapurna",
        ],
      },
      {
        type: "multiple",
        difficulty: "hard",
        category: "Geography",
        question:
          "The prefix Sino- (As in Sino-American) is used to refer to what nationality?",
        correct_answer: "Chinese",
        incorrect_answers: ["Japanese", "Russian", "Indian"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question: "How many countries are larger than Australia?",
        correct_answer: "5",
        incorrect_answers: ["4", "3", "6"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question: "How many timezones does Russia have?",
        correct_answer: "11",
        incorrect_answers: ["6", "24", "16"],
      },
      {
        type: "boolean",
        difficulty: "medium",
        category: "Geography",
        question:
          "&quot;Mongolia&quot; was a part of the now non-existent U.S.S.R.",
        correct_answer: "False",
        incorrect_answers: ["True"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Geography",
        question:
          "The longest shared border in the world can be found between which two nations?",
        correct_answer: "Canada and the United States",
        incorrect_answers: [
          "Chile and Argentina",
          "Russia and China",
          "India and Pakistan",
        ],
      },
      {
        type: "boolean",
        difficulty: "easy",
        category: "Geography",
        question: "Greenland is almost as big as Africa.",
        correct_answer: "False",
        incorrect_answers: ["True"],
      },
      {
        type: "multiple",
        difficulty: "hard",
        category: "Geography",
        question: "What is the name of the Canadian national anthem?",
        correct_answer: "O Canada",
        incorrect_answers: [
          "O Red Maple",
          "Leaf-Spangled Banner",
          "March of the Puck Drop",
        ],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question: "What is the smallest country in South America by area?",
        correct_answer: "Suriname",
        incorrect_answers: ["Brazil", "Uruguay", "Chile"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question:
          "The formerly East-Prussian city of K&ouml;nigsberg is known as which Russian City today?",
        correct_answer: "Kaliningrad",
        incorrect_answers: ["Kazan", "Kursk", "Krasnodar"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question: "Which country has three capital cities?",
        correct_answer: "South Africa",
        incorrect_answers: ["Somalia", "China", "United Kingdom"],
      },
      {
        type: "multiple",
        difficulty: "hard",
        category: "Geography",
        question: "Which country is completely landlocked by South Africa?",
        correct_answer: "Lesotho",
        incorrect_answers: ["Swaziland", "Botswana", "Zimbabwe"],
      },
      {
        type: "multiple",
        difficulty: "hard",
        category: "Geography",
        question: "What is the second-largest city in Lithuania?",
        correct_answer: "Kaunas",
        incorrect_answers: ["Panevėžys", "Vilnius", "Klaipėda"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Geography",
        question:
          "If soccer is called football in England, what is American football called in England?",
        correct_answer: "American football",
        incorrect_answers: ["Combball", "Handball", "Touchdown"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question: "Where is the &quot;Sonoran Desert&quot; located?",
        correct_answer: "North America",
        incorrect_answers: ["South America", "Asia", "Africa"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question: "What is the largest Muslim country in the world?",
        correct_answer: "Indonesia",
        incorrect_answers: ["Pakistan", "Saudi Arabia", "Iran"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question: "What is the fifth largest country by area?",
        correct_answer: "Brazil",
        incorrect_answers: ["United States", "Australia", "India"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Geography",
        question:
          "The derisive acronym &quot;PIIGS&quot; refers to which of the following European countries and their economic statuses?",
        correct_answer: "Portugal, Ireland, Italy, Greece, Spain",
        incorrect_answers: [
          "Poland, Iceland, Italy, Greece, Serbia",
          "Poland, Iceland, Italy, Greenland, Spain",
          "Portugal, Iceland, Ireland, Greece, Serbia",
        ],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Geography",
        question: "Which UK country features a dragon on their flag?",
        correct_answer: "Wales",
        incorrect_answers: ["England", "North Ireland", "Scotland"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question: "What was the most populous city in the Americas in 2015?",
        correct_answer: "S&atilde;o Paulo",
        incorrect_answers: ["New York", "Mexico City", "Los Angeles"],
      },
      {
        type: "boolean",
        difficulty: "medium",
        category: "Geography",
        question: "Gothenburg is the capital of Sweden.",
        correct_answer: "False",
        incorrect_answers: ["True"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Geography",
        question: "What is the capital of Spain?",
        correct_answer: "Madrid",
        incorrect_answers: ["Barcelona", "Sevilla", "Toledo"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Geography",
        question: "The body of the Egyptian Sphinx was based on which animal?",
        correct_answer: "Lion",
        incorrect_answers: ["Bull", "Horse", "Dog"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question: "What is the capital of Slovakia?",
        correct_answer: "Bratislava",
        incorrect_answers: ["Sofia", "Ljubljana", "Sarajevo"],
      },
      {
        type: "multiple",
        difficulty: "hard",
        category: "Geography",
        question: "Which country is the Taedong River in?",
        correct_answer: "North Korea",
        incorrect_answers: ["South Korea", "Japan", "China"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Geography",
        question: "Which country was NOT part of the Soviet Union?",
        correct_answer: "Romania",
        incorrect_answers: ["Turkmenistan", "Belarus", "Tajikistan"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question: "What tiny principality lies between Spain and France?",
        correct_answer: "Andorra",
        incorrect_answers: ["Liechtenstein", "Monaco", "San Marino"],
      },
      {
        type: "boolean",
        difficulty: "medium",
        category: "Geography",
        question: "The Sonoran Desert is located in eastern Africa.",
        correct_answer: "False",
        incorrect_answers: ["True"],
      },
      {
        type: "multiple",
        difficulty: "hard",
        category: "Geography",
        question:
          "What is the largest city and commercial capital of Sri Lanka?",
        correct_answer: "Colombo",
        incorrect_answers: ["Moratuwa", "Negombo", "Kandy"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question:
          "Which country inside the United Kingdom does NOT appear on its flag, the Union Jack?",
        correct_answer: "Wales",
        incorrect_answers: ["Scotland", "Ireland", "Isle of Wight"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question:
          "The Pyrenees mountains are located on the border of which two countries?",
        correct_answer: "France and Spain",
        incorrect_answers: [
          "Italy and Switzerland",
          "Norway and Sweden",
          "Russia and Ukraine",
        ],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question:
          "Which of these countries is not written in its native language?",
        correct_answer: "Slova&scaron;ko",
        incorrect_answers: ["Suomi", "Schweiz", "Ell&aacute;da"],
      },
      {
        type: "boolean",
        difficulty: "medium",
        category: "Geography",
        question: "Seoul is the capital of North Korea.",
        correct_answer: "False",
        incorrect_answers: ["True"],
      },
      {
        type: "multiple",
        difficulty: "easy",
        category: "Geography",
        question: "What is the capital of the US State of New York?",
        correct_answer: "Albany",
        incorrect_answers: ["Buffalo", "New York", "Rochester"],
      },
      {
        type: "boolean",
        difficulty: "easy",
        category: "Geography",
        question: "Tokyo is the capital of Japan.",
        correct_answer: "True",
        incorrect_answers: ["False"],
      },
      {
        type: "multiple",
        difficulty: "hard",
        category: "Geography",
        question:
          "What is the name of rocky region that spans most of eastern Canada?",
        correct_answer: "Canadian Shield",
        incorrect_answers: [
          "Rocky Mountains",
          "Appalachian Mountains",
          "Himalayas",
        ],
      },
      {
        type: "multiple",
        difficulty: "hard",
        category: "Geography",
        question:
          "The mountainous Khyber Pass connects which of the two following countries?",
        correct_answer: "Afghanistan and Pakistan",
        incorrect_answers: [
          "India and Nepal",
          "Pakistan and India",
          "Tajikistan and Kyrgyzstan",
        ],
      },
      {
        type: "multiple",
        difficulty: "hard",
        category: "Geography",
        question: "What city is known as the Rose Capital of the World?",
        correct_answer: "Tyler, Texas",
        incorrect_answers: [
          "San Diego, California",
          "Miami, Florida",
          "Anaheim, California",
        ],
      },
      {
        type: "multiple",
        difficulty: "hard",
        category: "Geography",
        question: "What year is on the flag of the US state Wisconsin?",
        correct_answer: "1848",
        incorrect_answers: ["1634", "1783", "1901"],
      },
      {
        type: "multiple",
        difficulty: "medium",
        category: "Geography",
        question: "Where is the area commonly known as the Bermuda Triangle?",
        correct_answer: "North Atlantic Ocean, between Florida and Puerto Rico",
        incorrect_answers: [
          "North Pacific Ocean, between Japan and the USA",
          "In the Caribbean Sea",
          "South Pacific Ocean, far off Chile",
        ],
      },
    ]