export const animalQuestions = [
  {
    type: "multiple",
    difficulty: "easy",
    category: "Animals",
    question: "How many teeth does an adult rabbit have?",
    correct_answer: "28",
    incorrect_answers: ["30", "26", "24"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Animals",
    question: "What type of creature is a Bonobo?",
    correct_answer: "Ape",
    incorrect_answers: ["Lion", "Parrot", "Wildcat"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Animals",
    question:
      "The Kākāpō is a large, flightless, nocturnal parrot native to which country?",
    correct_answer: "New Zealand",
    incorrect_answers: ["South Africa", "Australia", "Madagascar"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Animals",
    question:
      "Snakes and lizards are known to flick their tongue, this behavior is to?",
    correct_answer: "Capture scent particles",
    incorrect_answers: [
      "Taste the sweet air",
      "Threaten other species",
      "Attract female mates",
    ],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Animals",
    question:
      "Which of the following is another name for the &quot;Poecilotheria Metallica Tarantula&quot;?",
    correct_answer: "Gooty",
    incorrect_answers: ["Hopper", "Silver Stripe", "Woebegone"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question: "For what reason would a spotted hyena &quot;laugh&quot;?",
    correct_answer: "Nervousness",
    incorrect_answers: ["Excitement", "Aggression", "Exhaustion"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Animals",
    question:
      "What is the name of the copper-rich protein that creates the blue blood in the Antarctic octopus?",
    correct_answer: "Hemocyanin",
    incorrect_answers: ["Cytochrome", "Iron", "Methionine"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question:
      "What is the name of the family that the domestic cat is a member of?",
    correct_answer: "Felidae",
    incorrect_answers: ["Felinae", "Felis", "Cat"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Animals",
    question:
      "To which biological phylum do all mammals, birds and reptiles belong?",
    correct_answer: "Chordata",
    incorrect_answers: ["Echinodermata", "Annelida", "Placazoa"],
  },
  {
    type: "boolean",
    difficulty: "easy",
    category: "Animals",
    question: "Rabbits can&#039;t vomit.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    type: "boolean",
    difficulty: "medium",
    category: "Animals",
    question: "Tigers have one colour of skin despite the stripey fur.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    type: "boolean",
    difficulty: "easy",
    category: "Animals",
    question: "The internet browser Firefox is named after the Red Panda.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question: "What color/colour is a polar bear&#039;s skin?",
    correct_answer: "Black",
    incorrect_answers: ["White", "Pink", "Green"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Animals",
    question: "Which species is a &quot;mountain chicken&quot;?",
    correct_answer: "Frog",
    incorrect_answers: ["Chicken", "Horse", "Fly"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Animals",
    question: "Unlike on most salamanders, this part of a newt is flat?",
    correct_answer: "Tail",
    incorrect_answers: ["Head", "Teeth", "Feet"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Animals",
    question: "What is the name of a rabbit&#039;s abode?",
    correct_answer: "Burrow",
    incorrect_answers: ["Nest", "Den", "Dray"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question:
      "&quot;Decapods&quot; are an order of ten-footed crustaceans.  Which of these are NOT decapods?",
    correct_answer: "Krill",
    incorrect_answers: ["Lobsters", "Shrimp", "Crabs"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question:
      "What is the name for a male bee that comes from an unfertilized egg?",
    correct_answer: "Drone",
    incorrect_answers: ["Soldier", "Worker", "Male"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Animals",
    question: "By definition, where does an abyssopelagic animal live?",
    correct_answer: "At the bottom of the ocean",
    incorrect_answers: [
      "In the desert",
      "On top of a mountain",
      "Inside a tree",
    ],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question: "Which of the following is NOT a venomous snake?",
    correct_answer: "Reticulated python",
    incorrect_answers: [
      "Malayan Krait",
      "Yellow bellied sea snake",
      "Black mamba",
    ],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Animals",
    question: "What is the collective noun for vultures?",
    correct_answer: "Wake",
    incorrect_answers: ["Ambush", "Building", "Gaze"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question:
      "What is the common term for bovine spongiform encephalopathy (BSE)?",
    correct_answer: "Mad Cow disease",
    incorrect_answers: [
      "Weil&#039;s disease",
      "Milk fever",
      "Foot-and-mouth disease",
    ],
  },
  {
    type: "boolean",
    difficulty: "medium",
    category: "Animals",
    question:
      "The Ceratosaurus, a dinosaur known for having a horn on the top of its nose, is also known to be a decendent of the Tyrannosaurus Rex.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    type: "boolean",
    difficulty: "medium",
    category: "Animals",
    question: "Sea sponges can have hearts.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Animals",
    question: "How many known living species of hyenas are there?",
    correct_answer: "4",
    incorrect_answers: ["8", "2", "6"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question: "What is the scientific name of the Common Chimpanzee?",
    correct_answer: "Pan troglodytes",
    incorrect_answers: ["Gorilla gorilla", "Pan paniscus", "Panthera leo"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question: "What is the collective noun for bears?",
    correct_answer: "Sloth",
    incorrect_answers: ["Drove", "Tribe", "Husk"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Animals",
    question: "What bird is born with claws on its wing digits?",
    correct_answer: "Hoatzin",
    incorrect_answers: ["Cormorant", "Cassowary", "Secretary bird"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Animals",
    question: "What is the collective noun for a group of crows?",
    correct_answer: "Murder",
    incorrect_answers: ["Pack", "Gaggle", "Herd"],
  },
  {
    type: "boolean",
    difficulty: "medium",
    category: "Animals",
    question: "An octopus can fit through any hole larger than its beak.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question: "Which of these species is not extinct?",
    correct_answer: "Komodo dragon",
    incorrect_answers: [
      "Japanese sea lion",
      "Tasmanian tiger",
      "Saudi gazelle",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Animals",
    question: "What do you call a baby bat?",
    correct_answer: "Pup",
    incorrect_answers: ["Cub", "Chick", "Kid"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Animals",
    question: "Which of these is a colony of polyps and not a jellyfish?",
    correct_answer: "Portuguese Man-of-War",
    incorrect_answers: ["Sea Wasp", "Irukandji", "Sea Nettle"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Animals",
    question: "How many legs do butterflies have?",
    correct_answer: "6",
    incorrect_answers: ["2", "4", "0"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Animals",
    question:
      "What was the name of the Ethiopian Wolf before they knew it was related to wolves?",
    correct_answer: "Simien Jackel",
    incorrect_answers: ["Ethiopian Coyote", "Amharic Fox", "Canis Simiensis"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Animals",
    question: "Hippocampus is the Latin name for which marine creature?",
    correct_answer: "Seahorse",
    incorrect_answers: ["Dolphin", "Whale", "Octopus"],
  },
  {
    type: "boolean",
    difficulty: "easy",
    category: "Animals",
    question: "Kangaroos keep food in their pouches next to their children.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    type: "boolean",
    difficulty: "medium",
    category: "Animals",
    question:
      "You can tell the age of a ladybird by counting the spots on his back.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Animals",
    question: "Which species of Brown Bear is not extinct?",
    correct_answer: "Syrian Brown Bear",
    incorrect_answers: [
      "California Grizzly Bear",
      "Atlas Bear",
      "Mexican Grizzly Bear",
    ],
  },
  {
    type: "boolean",
    difficulty: "easy",
    category: "Animals",
    question:
      "The Axolotl is an amphibian that can spend its whole life in a larval state.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    type: "boolean",
    difficulty: "easy",
    category: "Animals",
    question:
      "Rabbits can see what&#039;s behind themselves without turning their heads.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question:
      "Which animal was part of an Russian domestication experiment in 1959?",
    correct_answer: "Foxes",
    incorrect_answers: ["Pigeons", "Bears", "Alligators"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Animals",
    question: "What scientific suborder does the family Hyaenidae belong to?",
    correct_answer: "Feliformia",
    incorrect_answers: ["Haplorhini", "Caniformia", "Ciconiiformes"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question:
      "A carnivorous animal eats flesh, what does a nucivorous animal eat?",
    correct_answer: "Nuts",
    incorrect_answers: ["Nothing", "Fruit", "Seaweed"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question: "What is the scientific name for the &quot;Polar Bear&quot;?",
    correct_answer: "Ursus Maritimus",
    incorrect_answers: ["Polar Bear", "Ursus Spelaeus", "Ursus Arctos"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question:
      "Which of the following is true when alligators are behaving territorially?",
    correct_answer: "They bellow while showing their tail and neck",
    incorrect_answers: [
      "Open their jaws while making a clicking noise",
      "They run full force at the threat",
      "Slap their tails on the ground",
    ],
  },
  {
    type: "boolean",
    difficulty: "medium",
    category: "Animals",
    question: "Hyenas are more closely related to cats than to dogs.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question: "Cashmere is the wool from which kind of animal?",
    correct_answer: "Goat",
    incorrect_answers: ["Sheep", "Camel", "Llama"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question: "What does &quot;hippopotamus&quot; mean and in what langauge?",
    correct_answer: "River Horse (Greek)",
    incorrect_answers: [
      "River Horse (Latin)",
      "Fat Pig (Greek)",
      "Fat Pig (Latin)",
    ],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Animals",
    question: "What are the scales on all snakes and most lizards are made of?",
    correct_answer: "Keratin",
    incorrect_answers: ["Ecdysis", "Epidermis", "Ankyloglossia"],
  },
];
